# Large 3D Gridworld Configuration Parameters
create_gridworld_node:
  ros__parameters:
    # Grid dimensions - Large 3D world
    grid_width: 100
    grid_height: 100  
    grid_depth: 20
    
    # Grid resolution (meters per cell)
    grid_resolution: 1.0
    
    # Publishing rate (Hz)
    publish_rate: 5.0  # Lower rate for large world to reduce computational load
    
    # Obstacle configuration - Flattened array format
    # Each obstacle region: [start_x, start_y, start_z, end_x, end_y, end_z]
    obstacle_regions: [
      30, 30, 0, 70, 70, 15,   # Large central building complex
      10, 10, 0, 25, 25, 8,    # Smaller building - bottom left
      75, 10, 0, 90, 25, 8,    # Smaller building - bottom right
      10, 75, 0, 25, 90, 8,    # Smaller building - top left
      75, 75, 0, 90, 90, 8,    # Smaller building - top right
      45, 15, 0, 55, 25, 19,   # Vertical obstacle (tower) - bottom
      45, 75, 0, 55, 85, 19    # Vertical obstacle (tower) - top
    ]
    
    # Agent positions - Flattened array format
    # Each agent position: [x, y, z]
    agent_positions: [
      5, 5, 0,       # Agent 1
      95, 5, 0,      # Agent 2
      5, 95, 0,      # Agent 3
      95, 95, 0,     # Agent 4
      50, 5, 10,     # Agent 5 (elevated)
      50, 95, 10,    # Agent 6 (elevated)
      25, 50, 5,     # Agent 7 (mid-level)
      75, 50, 5      # Agent 8 (mid-level)
    ]

    induct_stations: [
      5, 15, 0, 1,        # Induct station 1 - bottom left, ground level
      95, 15, 0, 2,       # Induct station 2 - bottom right, ground level
      5, 85, 0, 3,        # Induct station 3 - top left, ground level
      95, 85, 0, 4,       # Induct station 4 - top right, ground level
      25, 5, 5, 5,        # Induct station 5 - bottom, mid-level
      75, 5, 5, 6,        # Induct station 6 - bottom, mid-level
      25, 95, 10, 7,      # Induct station 7 - top, high level
      75, 95, 10, 8,      # Induct station 8 - top, high level
      50, 50, 16, 9,      # Induct station 9 - center, very high level
      15, 50, 2, 10       # Induct station 10 - left center, low-mid level
    ]
    
    # Eject (exit) stations - Flattened array format
    # Each station: [x, y, z, station_id]
    eject_stations: [
      15, 5, 0, 1,        # Eject station 1 - bottom area, ground level
      85, 5, 0, 2,        # Eject station 2 - bottom area, ground level
      15, 95, 0, 3,       # Eject station 3 - top area, ground level
      85, 95, 0, 4,       # Eject station 4 - top area, ground level
      5, 50, 8, 5,        # Eject station 5 - left center, high level
      95, 50, 8, 6,       # Eject station 6 - right center, high level
      50, 15, 12, 7,      # Eject station 7 - bottom center, very high
      50, 85, 12, 8,      # Eject station 8 - top center, very high
      25, 25, 15, 9,      # Eject station 9 - lower left, very high
      75, 75, 15, 10      # Eject station 10 - upper right, very high
    ]
    
    # Visualization settings
    visualization:
      # Node visualization
      node_scale: 0.1         # Smaller points for large world
      node_color: [0.0, 1.0, 0.0, 0.3]  # More transparent for performance
      
      # Edge visualization  
      edge_width: 0.05         # Thinner lines for large world
      edge_color: [0.0, 0.0, 1.0, 0.2]  # More transparent
      
      # Obstacle visualization
      obstacle_scale: 0.95     # Nearly full scale
      obstacle_color: [1.0, 0.0, 0.0, 0.8]  # Red, mostly opaque
      
      # Agent visualization
      agent_scale: 0.8         # Larger agents to be visible in large world
      agent_color: [1.0, 0.0, 1.0, 1.0]   # Magenta for 3D contrast

      # Induct station visualization
      induct_station_scale: 1.2    # Larger for visibility in big 3D world
      induct_station_color: [0.0, 0.5, 1.0, 1.0]  # Light blue, fully opaque
      
      # Eject station visualization
      eject_station_scale: 1.2     # Larger for visibility in big 3D world
      eject_station_color: [1.0, 0.5, 0.0, 1.0]   # Orange, fully opaque
    
    # Frame settings
    frame_id: "map"
    
    # Topic names
    topics:
      nodes: "gridworld/nodes"
      edges: "gridworld/edges" 
      obstacles: "gridworld/obstacles"
      agents: "gridworld/agents"
      induct_stations: "gridworld/induct_stations"
      eject_stations: "gridworld/eject_stations"